declare const styles: {
	readonly css: string;
	readonly footer: string;
	readonly gameArea: string;
	readonly header: string;
	readonly lateNight: string;
	readonly main: string;
	readonly menuBtn: string;
	readonly notification: string;
	readonly notificationVisible: string;
	readonly phoneBtn: string;
	readonly phoneDot: string;
	readonly phoneDotPulse: string;
	readonly phoneDotUrgent: string;
	readonly phoneDotVisible: string;
	readonly phoneIcon: string;
	readonly points: string;
	readonly skipBtn: string;
	readonly slot: string;
	readonly slotUsed: string;
	readonly slots: string;
	readonly taskList: string;
	readonly taskListContainer: string;
	readonly timeBlock: string;
	readonly title: string;
};
export default styles;
