declare const styles: {
	readonly btn: string;
	readonly btnDanger: string;
	readonly collapsed: string;
	readonly container: string;
	readonly content: string;
	readonly controls: string;
	readonly header: string;
	readonly headerRight: string;
	readonly key: string;
	readonly row: string;
	readonly rowTotal: string;
	readonly section: string;
	readonly title: string;
	readonly toggle: string;
	readonly value: string;
	readonly valueHidden: string;
	readonly valueLarge: string;
	readonly valueModifier: string;
	readonly valueNote: string;
	readonly valueNumber: string;
};
export default styles;
